# This is a basic workflow to help you get started with Actions
name: Weekly Discovery parsing

# Controls when the workflow will run
on:
  schedule:
    cron:
      - 0 9 * * 1
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.0"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install packages
        run: Rscript -e 'install.packages(c("spotifyr", "dplyr"))'
      - name: Run script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: Rscript main.R