name: Weekly Discovery parsing

on:
  schedule:
    - cron: "0 9 * * 1" # Run every Monday at 9 AM
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.1.0"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install packages
        run: Rscript -e 'install.packages(c("spotifyr", "dplyr"))'
      - name: Run script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: Rscript main.R